package root.screens.verifyactivity;

import java.awt.EventQueue;
import java.awt.event.ActionListener;
import root.Navigable;
import root.Screen;


public class VerifyActivityView extends Screen {
    final VerifyActivityModel model;
    
    /**
     * Creates new form VerifyActivityView
     * @param nav
     * @param model
     */
    public VerifyActivityView(Navigable nav, VerifyActivityModel model) {
        super(nav);
        this.model = model == null ? new VerifyActivityModel(0, "", "", "", "", 0, false, 0, "", null) : model;
        initComponents();
        if (model == null) {
            EventQueue.invokeLater(() -> {
                super.showErrorMsg("Activity not found", "Unable to fetch activity");
                nav.goHome();
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel titleLabel = new javax.swing.JLabel();
        javax.swing.JLabel idLabel = new javax.swing.JLabel();
        idValueLabel = new javax.swing.JLabel();
        javax.swing.JLabel noteLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteTextArea = new javax.swing.JTextArea();
        javax.swing.JLabel areaLabel = new javax.swing.JLabel();
        areaValueLabel = new javax.swing.JLabel();
        javax.swing.JLabel typologyLabel = new javax.swing.JLabel();
        typologyValueLabel = new javax.swing.JLabel();
        javax.swing.JLabel timeLabel = new javax.swing.JLabel();
        timeValueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        skillList = new javax.swing.JList<>();
        javax.swing.JLabel weekLabel = new javax.swing.JLabel();
        weekValueLabel = new javax.swing.JLabel();
        javax.swing.JLabel descLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        descTextArea = new javax.swing.JTextArea();
        javax.swing.JLabel smpLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel smpLabel2 = new javax.swing.JLabel();

        backBtn.setText("back");

        homeBtn.setText("home");

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLabel.setText("Verify Activity");

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        idLabel.setForeground(new java.awt.Color(102, 102, 102));
        idLabel.setText("ID");

        idValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idValueLabel.setText("" + model.getId());

        noteLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        noteLabel.setForeground(new java.awt.Color(102, 102, 102));
        noteLabel.setText("Workspace note");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        noteTextArea.setColumns(20);
        noteTextArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        noteTextArea.setLineWrap(true);
        noteTextArea.setRows(5);
        noteTextArea.setText(model.getNotes());
        noteTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(noteTextArea);

        areaLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        areaLabel.setForeground(new java.awt.Color(102, 102, 102));
        areaLabel.setText("Area");

        areaValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        areaValueLabel.setText(model.getArea());

        typologyLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        typologyLabel.setForeground(new java.awt.Color(102, 102, 102));
        typologyLabel.setText("Typology");

        typologyValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        typologyValueLabel.setText(model.getTypology());

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(102, 102, 102));
        timeLabel.setText("Estimated intevetion time");

        timeValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        timeValueLabel.setText(model.getTime() + "m");

        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Skills needed", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        skillList.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        skillList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        skillList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "    • Skill list not implemented yet" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        skillList.setEnabled(false);
        jScrollPane2.setViewportView(skillList);

        weekLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        weekLabel.setForeground(new java.awt.Color(102, 102, 102));
        weekLabel.setText("Week number");

        weekValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        weekValueLabel.setText("" + model.getWeek());

        descLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        descLabel.setForeground(new java.awt.Color(102, 102, 102));
        descLabel.setText("Intervention description");

        forwardBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        forwardBtn.setText("FORWARD");

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descTextArea.setEditable(false);
        descTextArea.setColumns(20);
        descTextArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descTextArea.setLineWrap(true);
        descTextArea.setRows(5);
        descTextArea.setText(model.getDescription());
        descTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(descTextArea);

        smpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/download-solid.png"))); // NOI18N
        smpBtn.setEnabled(false);

        smpLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        smpLabel1.setForeground(new java.awt.Color(51, 51, 51));
        smpLabel1.setText("Standard Maintenance");

        smpLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        smpLabel2.setForeground(new java.awt.Color(51, 51, 51));
        smpLabel2.setText("Procedure File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titleLabel)
                        .addGap(112, 112, 112)
                        .addComponent(homeBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noteLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descLabel)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLabel)
                                    .addComponent(areaLabel)
                                    .addComponent(typologyLabel)
                                    .addComponent(weekLabel))
                                .addGap(177, 177, 177))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(typologyValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(areaValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(weekValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(timeLabel)
                                        .addGap(59, 59, 59))
                                    .addComponent(timeValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(smpLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(smpLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(smpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(forwardBtn)
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(backBtn)
                    .addComponent(homeBtn))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idValueLabel)
                        .addGap(13, 13, 13)
                        .addComponent(weekLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weekValueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(areaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(areaValueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typologyLabel))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typologyValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(smpLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smpLabel2))
                    .addComponent(smpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeValueLabel)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(noteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(forwardBtn)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void addBackBtnListener(ActionListener al) {
        backBtn.addActionListener(al);
    }
    
    public void addHomeBtnListener(ActionListener al) {
        homeBtn.addActionListener(al);
    }
    
    public void addForwardBtnListener(ActionListener al) {
        forwardBtn.addActionListener(al);
    }
    
    public void addSmpBtnListener(ActionListener al) {
        smpBtn.addActionListener(al);
    }
    
    public String getTextAreaNotes() {
        return noteTextArea.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaValueLabel;
    protected final javax.swing.JButton backBtn = new javax.swing.JButton();
    private javax.swing.JTextArea descTextArea;
    protected final javax.swing.JButton forwardBtn = new javax.swing.JButton();
    protected final javax.swing.JButton homeBtn = new javax.swing.JButton();
    private javax.swing.JLabel idValueLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea noteTextArea;
    private javax.swing.JList<String> skillList;
    protected final javax.swing.JButton smpBtn = new javax.swing.JButton();
    private javax.swing.JLabel timeValueLabel;
    private javax.swing.JLabel typologyValueLabel;
    private javax.swing.JLabel weekValueLabel;
    // End of variables declaration//GEN-END:variables
}
